### ISSUE TITLE
Unused function parameters

### ISSUE THREAD

**Issue by lootboi** [Byte-Masons/Reliquary#25]
![Screenshot 2022-09-28 112049](https://user-images.githubusercontent.com/96591695/192848012-4b7120f6-704b-45c3-864d-b59f9f43246b.png)

When compiling, there are numerous unused function parameters. Will these have some usage in the future or can they just be removed?

**Comment by Zokunei** [comment]
The parameters are passed to the interfaces so that overriding contracts can take advantage of them for added functionality. It is not envisioned for there to be only one implementation of a Rewarder, NFTDescriptor, or EmissionCurve.

**Comment by Zokunei** [comment]
Issue addressed in commit [2340a00](https://github.com/Byte-Masons/Reliquary/commit/2340a00956fefb003132c3dce89ef658c5fdc216).
