### ISSUE TITLE
Add support to typescript

### ISSUE THREAD

**Issue by StErMi** [Byte-Masons/Reliquary#4]
I haven't made any PR because I'm external to the team but I would like to give my 2cents.

Having support to typescripts help a lot in two things:

1) you're not blind when you write tests, everything is automatically suggested and typesafe. The tradeoff on slowness when you run test/build is not so much a huge deal compared to the benefits
2) it allows you to generate typescript-ready interfaces SDK for your frontend applications easily distributable as an npm package (so external services can install them as versioned dependencies).

I have a solidity-template project that is easily forkable for that but it's really a matter of fact of creating a `tsconfig`, updating the hardhat config file to .ts (and updating the content), and adding some dependencies like 

```
@typechain/ethers-v5
@typechain/hardhat
typechain
```

If you want to follow my solidity-template you can head over here: https://github.com/StErMi/solidity-template

**Comment by Zokunei** [comment]
TypeScript is no longer needed as all tests/scripts are through Foundry.
