### ISSUE TITLE
Adding support to husky

### ISSUE THREAD

**Issue by StErMi** [Byte-Masons/Reliquary#5]
Another 2 cents, it's not cool to have commits that do not build/fail tests that have been merged with code. 

https://www.npmjs.com/package/husky allows you to create automation before commit/push. 

In this case husky can be used to attach some automation before commit/push like:

- lint the code
- prettify the code
- build the contract (and see if it fails with warning/errors)
- run tests

if some of these commands fail with warning/error the command (commit/push) fails.

I've never done this for a solidity project but I don't think it's a difficult task. Another option would be to attach all these checks on the CI pipeline of git but I think that it's a second step that should be done after being sure that your local code does not fail.

**Comment by Zokunei** [comment]
addressed in commit [500f72ab12351f87606d48f99f0b3f8859580e04](https://github.com/Byte-Masons/Reliquary/commit/500f72ab12351f87606d48f99f0b3f8859580e04)
